### ISSUE TITLE
Calculation of maximum order for HOA does not distinguish between even/odd numer of secondary sources

### ISSUE THREAD

**Issue by spors** [sfstoolbox/sfs-python#105]
See https://github.com/sfstoolbox/sfs-python/blob/3ae7a9ffdfa2775f0ce55b2d6c74727be0be4632/sfs/mono/drivingfunction.py#L795-L797

**Comment by mgeier** [comment]
This is moved to `util.max_order_circular_harmonics()` in  #45 and changed to

```python
return (N - 1) // 2
```

This should fix the issue, right?

**Comment by spors** [comment]
No we have to distingusih between even/odd `N` (see sfs-matlab for instance). I will fix the code.

**Comment by spors** [comment]
Yes that fixes the issue!
