### ISSUE TITLE
Examples for WFS or NFCHOA

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-python#134]
Maybe, I overlooked a pull request, but in the documentation of the current master, the following can be found under "Examples":
* Modal Room Acoustics
* Mirror Image Sources and the Sound Field in a Rectangular Room
* Animations of a Pulsating Sphere
* Example Python Scripts

It seems a little bit strange to me that no WFS or NFC-HOA appear there, maybe we move one of the "Example Python Scripts" that deals with sound field synthesis in an notebook example?

**Comment by fs446** [comment]
Yeah, that's weird.
Maybe we could take this one
https://github.com/spatialaudio/sfs-with-local-wavenumber-vector-concept/blob/master/WFS_vs_NFCHOA.ipynb

I've started it yesterday for my DAGA project. We only have to adapt this to work with the master branch (exchanging frequency point_25d) and comment a little bit more.

**Comment by mgeier** [comment]
@hagenw You didn't overlook it, we currently don't have such examples.

I've slightly touched on this topic in #108:

> We could also split the example script into multiple parts and turn some of them into notebooks?
