### ISSUE TITLE
Update readthedocs config?

### ISSUE THREAD

**Issue by mgeier** [sfstoolbox/sfs-python#164]
The docs build on RTD has been broken for a few months now, see https://readthedocs.org/projects/sfs-python/builds/

There's this error message when creating the `conda` environment:

```
Collecting package metadata (repodata.json): ...working... Killed


Command killed due to excessive memory consumption
```

Probably we should switch away from `conda` again?

We initially switched to `conda` years ago: #2.

I guess the limitations we had at that time are now long gone ...

**Comment by mgeier** [comment]
I just heard that RTD has upgraded their servers, and now it indeed works again: https://readthedocs.org/projects/sfs-python/builds/

So it's not strictly necessary to switch away from `conda` now, but we might do it anyway at some point.

**Comment by chris-hld** [comment]
I remember having the same issue. Not sure but I think changing the channel from `conda-forge` to `defaults` solved it.

**Comment by hagenw** [comment]
Seems to be that the builds are working again: https://readthedocs.org/projects/sfs-python/builds/12313514/

**Comment by fs446** [comment]
see mods for release 0.6.2
I guess we can close this for now.
