### ISSUE TITLE
Documentation for 0.6.0 not online

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-python#171]
When heading to https://sfs-python.readthedocs.io/ one is seeing the documentation for version 0.5.0 whereas 0.6.0 is our latest release.

**Comment by mgeier** [comment]
The last point in the release checklist is ab out RTD: https://sfs-python.readthedocs.io/en/0.5.0/contributing.html#creating-a-new-release

@spors did the last release and apparently didn't do the whole checklist.

**Comment by fs446** [comment]
0.6.0 cannot be built on servers due to meanwhile newer versions of sphinx, mathjax. I guess we have to live with missing documentation?
However, by great support of mgeier the release 0.6.2 is alive with full documentation.
Therefore, I guess we close this issue.
