### ISSUE TITLE
Remove x0 from plane wave?

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-python#4]
In the [current implementation of a plane wave](https://github.com/sfstoolbox/sfs-python/blob/master/sfs/mono/source.py#L319) we use `x0` besides `n0`, which is a little bit confusing as you would normally suspect that `n0` is everything you need to specify a plane wave.

Is there a reason why we have `x0` in addition (it is simply substracted from the grid) or can we just remove it?

**Comment by fietew** [comment]
I think, one can define the point or more precisely the plane of zero phase/zero delay with x0.

**Comment by hagenw** [comment]
I'm not sure if we really need this feature.
And if, we should update the formula, which is at the moment:
```
G(x, w) = e^(-i w/c n x)
```
and does not contain any `x0`.

**Comment by spors** [comment]
* This feature could be important to simulate spatially shifted plane wave decompositions.
* Another reason for the parameter x_0 is that all (secondary) sources should have the same ore arguments so that they can be exchanged easily in `synthesized.generic(..., source=)`

**Comment by hagenw** [comment]
OK, this sounds reasonable. Then we should keep it and update only the documentation.
