### ISSUE TITLE
Monofrequent dipole source example plot

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-python#50]
The plot of the mono-frequent dipole source has a (normalization?) issue in the current version.

![frequency-domain-9_new](https://user-images.githubusercontent.com/173624/33483499-0fbc2f18-d696-11e7-9390-68887913bf19.png)

http://python.sfstoolbox.org/en/latest/frequency-domain.html#sfs.mono.source.point_dipole

Before it was

![frequency-domain-9_old](https://user-images.githubusercontent.com/173624/33483527-25a13936-d696-11e7-817c-3501b66bf74d.png)

http://python.sfstoolbox.org/en/0.3.1/#sfs.mono.source.point_dipole

**Comment by hagenw** [comment]
This is a strange one and seems to originate in matplotlib or numpy. The calculated sound fields are identical besides deviations in the order of e-26.

Plotting the field calculated by the master branch with numpy==1.14.0 and matplotlib==2.1.2 results in the first figure. Doing the same with numpy==1.13.1 and matplotlib==2.0.2 results in the second figure.

The difference between sfs 0.3.1 and its master branch comes from slightly different requirement files, which I used to install the packages.

**Comment by trettberg** [comment]
It seems to be a matplotlib 2.1 issue, I just asked over there.
https://github.com/matplotlib/matplotlib/issues/10567
