### ISSUE TITLE
Example in documentation of sfs.mono.source.point_velocity shows sound pressure of a dipole

### ISSUE THREAD

**Issue by spors** [sfstoolbox/sfs-python#64]
The example in documentation of `sfs.mono.source.point_velocity` shows sound pressure of a dipole. See http://python.sfstoolbox.org/en/0.4.0/frequency-domain.html#sfs.mono.source.point_velocity

**Comment by mgeier** [comment]
The docs are somehow messed up on RTD. The functions were in alphabetical order, even though they should be in the order from the source file.

I've "wiped" and re-built the docs for `master` and `0.4.0` on RTD. Now the order of functions is correct, but the plot images are completely mixed up ... when I build it locally, it looks fine.

**Comment by hagenw** [comment]
If I look at http://python.sfstoolbox.org/en/0.4.0/frequency-domain.html#sfs.mono.source.point_velocity the figures are not mixed up, or do I miss something?

**Comment by mgeier** [comment]
Indeed, now it looks OK! This may have been a caching issue on my browser (or on the server?).

AFAICT, now everything looks as expected, I think we can close this issue.
